### PR TITLE
[SERVICE-527] Font loader & SCSS

### PR DESCRIPTION
**Pull request by ottah**
- Match Notifications service folder structure
- Convert CSS to SCSS
- Use Nunito font & add root style files

### CODE REVIEW

**Review by bryangaleopenfin — COMMENTED** [review]
I assume the demo apps are staying as plain old CSS?

There's two w3.css files left - one under provider, one under demo. Is the demo one still meant to be there?

**Comment by ottah** [comment]
@bryangaleOF Yeah I left the demo apps as is.

**Comment by bryangaleopenfin** [comment]
Ah, meant to write - "There's two w3.css files left - one under provider, one under demo. Is the **provider** one still meant to be there?" 🙂

**Comment by ottah** [comment]
@bryangaleOF Removed the unused `w3.css` file in the provider folder.

**Review by bryangaleopenfin — APPROVED** [review]

**Review by tomrobertsOF — APPROVED** [review]

**Pull request merged**
