### PR TITLE
[SERVICE-411] Add OpenFin Licence key to all service windows

### PR DESCRIPTION
**Pull request by rypete**
Adds the services license key to all fdc3 app.json files, as well as the app.json middleware.

### CODE REVIEW

**Review by bryangaleopenfin — COMMENTED** [review]
licenseKey need in test-app-*.json?

**Comment by rypete** [comment]
@bryangaleOF That doesn't exist...

**Review by pjbroadbent — APPROVED** [review]

**Comment by bryangaleopenfin** [comment]
@ryanpetersonOF Under `res/test/configs`

**Comment by rypete** [comment]
@bryangaleOF Its not in develop in which case whoever adds it will need to add in the license key

https://github.com/HadoukenIO/fdc3-service/tree/develop/res/test

**Review by ottah — APPROVED** [review]

**Pull request merged**
